import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import Footer from "./components/Footer/Footer";
import Header from "./components/Header/Header";



const bilo = localFont({
  src: [
    {
      path: "../public/fonts/bilo/fonnts.com-Bilo.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/bilo/fonnts.com-Bilo_Bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts/bilo/fonnts.com-Bilo_Black.otf",
      weight: "900",
      style: "normal",
    },
    {
      path: "../public/fonts/bilo/fonnts.com-Bilo_ExtraBold.otf",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-bilo", 
});





export const metadata = {
  title: "HomeU",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${bilo.variable} antialiased`}
      >
        <Header />

        {children}

        <Footer />
      </body>
    </html>
  );
}
